---
- name: "Automate Docker Build using Ansible"
  hosts: localhost
  tasks:
  - name: stop running container 
    command: docker stop django-container 
    ignore_errors: yes

  - name: remove stopped container 
    command: docker rm django-container
    ignore_errors: yes

### Make sure to change the image name in the next tasks with your dockerhub username and repository name

  - name: remove used image 
    command: docker rmi polling-app
    ignore_errors: yes

  - name: build new image 
    command: docker build -t polling-app .

### Make sure to change the image name in the previous tasks with your dockerhub username and repository name

  - name: run new container
    command: docker run -d --name django-container -p 8000:8000 polling-app

  - name: run migration inside container
    command: docker exec -i django-container sh -c "python3 manage.py makemigrations && python3 manage.py migrate"
